version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install --user tox
      - run: ~/.local/bin/tox

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
