version: 2
jobs:
  test37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install --user nox
      - run: ~/.local/bin/nox
  test38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install --user nox
      - run: ~/.local/bin/nox  
  test39:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: pip install --user nox
      - run: ~/.local/bin/nox            

workflows:
  version: 2
  build_and_test:
    jobs:
      - test37
      - test38
      - test39
