version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: pip install --user nox
      - run: ~/.local/bin/nox

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
